version: '3'

services:
  algod:
    container_name: "${ALGOD_CONTAINER:-algorand-sandbox-algod}"
    build:
      context: .
      dockerfile: ./images/algod/Dockerfile
      args:
        CHANNEL: "${ALGOD_CHANNEL}"
        URL: "${ALGOD_URL}"
        BRANCH: "${ALGOD_BRANCH}"
        SHA: "${ALGOD_SHA}"
        BOOTSTRAP_URL: "${NETWORK_BOOTSTRAP_URL}"
        GENESIS_FILE: "${NETWORK_GENESIS_FILE}"
        TEMPLATE: "${NETWORK_TEMPLATE:-images/algod/template.json}"
        NETWORK_NUM_ROUNDS: "${NETWORK_NUM_ROUNDS:-30000}"
        NODE_ARCHIVAL: "${NODE_ARCHIVAL}"
        TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        ALGOD_PORT: "4001"
        KMD_PORT: "4002"
        CDT_PORT: "9392"
        DROP_FOLLOWER: "${INDEXER_DISABLED}"
    ports:
      - ${ALGOD_PORT:-4001}:4001
      - ${KMD_PORT:-4002}:4002
      - ${CDT_PORT:-9392}:9392
    networks:
      - follower

networks:
  follower:
